import { useQuery } from '@tanstack/react-query';
import { supabase } from '../lib/supabase';
import { DealTask, DealMilestone, TaskPriority } from '../types';
import { generateId } from '../utils/helpers';
import { generateTasksForMilestone } from '../utils/taskTemplates';

// ── Types ────────────────────────────────────────────────────────────────────

interface RawTemplateItem {
  id: string;
  title: string;
  category: string;
  priority: string | null;
  due_days_from_contract: number | null;
  sort_order: number;
  is_required: boolean;
}

interface RawTemplate {
  id: string;
  name: string;
  pipeline_stage: string | null;   // milestone key this template fires on
  deal_type: string | null;        // 'buyer' | 'seller' | 'both' | null (null = all)
  mls_id: string | null;
  org_id: string | null;
  checklist_template_items: RawTemplateItem[];
}

// ── Hook ─────────────────────────────────────────────────────────────────────

/**
 * Fetches all milestone-type task templates (only those linked to a specific
 * pipeline_stage/milestone key). Used by WorkspaceOverview to resolve which
 * tasks to auto-generate when advancing a deal milestone.
 */
export function useMilestoneTaskLookup() {
  return useQuery<RawTemplate[]>({
    queryKey: ['milestone-task-lookup'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('checklist_templates')
        .select(`
          id, name, pipeline_stage, deal_type, mls_id, org_id,
          checklist_template_items (
            id, title, category, priority, due_days_from_contract, sort_order, is_required
          )
        `)
        .eq('checklist_type', 'milestone')
        .eq('is_active', true)
        .not('pipeline_stage', 'is', null);   // only templates tied to a milestone
      if (error) throw error;
      return (data ?? []) as RawTemplate[];
    },
    staleTime: 60_000,
  });
}

// ── Resolver ─────────────────────────────────────────────────────────────────

/**
 * Pick the best matching template for a given milestone + deal context,
 * then convert its items to DealTask[].
 *
 * Scoring (higher = more specific):
 *   +4  org_id matches deal's org
 *   +2  mls_id matches deal's MLS board
 *   +1  deal_type matches deal's transaction type
 *
 * Falls back to the hardcoded TEMPLATES if no DB template exists.
 */
export function resolveTasksForMilestone(
  milestoneKey: string,
  templates: RawTemplate[],
  orgId: string | undefined,
  mlsId: string | undefined,
  transactionType: string | undefined,
  contractDate: string | undefined,
): DealTask[] {
  // filter to this milestone
  const candidates = templates.filter(t => t.pipeline_stage === milestoneKey);

  if (candidates.length === 0) {
    return generateTasksForMilestone(milestoneKey as DealMilestone);
  }

  // deal_type matching helper
  const dealTypeMatches = (tplType: string | null): boolean => {
    if (!tplType || tplType === 'both') return true;
    if (tplType === 'buyer') return transactionType === 'buyer' || transactionType === 'dual';
    if (tplType === 'seller') return transactionType === 'seller' || transactionType === 'dual' || transactionType === 'listing';
    return tplType === transactionType;
  };

  const filtered = candidates.filter(t => dealTypeMatches(t.deal_type));
  if (filtered.length === 0) {
    return generateTasksForMilestone(milestoneKey as DealMilestone);
  }

  // score + sort
  const scored = filtered
    .map(t => ({
      ...t,
      score:
        (t.org_id != null && t.org_id === orgId ? 4 : 0) +
        (t.mls_id != null && t.mls_id === mlsId ? 2 : 0) +
        (t.deal_type != null ? 1 : 0),
    }))
    .sort((a, b) => b.score - a.score);

  const best = scored[0];
  const items = [...(best.checklist_template_items || [])].sort(
    (a, b) => a.sort_order - b.sort_order,
  );

  if (items.length === 0) {
    return generateTasksForMilestone(milestoneKey as DealMilestone);
  }

  return items.map((item): DealTask => {
    let dueDate: string;
    if (item.due_days_from_contract != null && contractDate) {
      const base = new Date(contractDate + 'T00:00:00');
      base.setDate(base.getDate() + item.due_days_from_contract);
      dueDate = base.toISOString().slice(0, 10);
    } else {
      const d = new Date();
      d.setDate(d.getDate() + (item.due_days_from_contract ?? 3));
      dueDate = d.toISOString().slice(0, 10);
    }

    return {
      id: generateId(),
      title: item.title,
      dueDate,
      priority: ((item.priority as TaskPriority) || 'medium'),
      category: item.category || 'General',
      milestone: milestoneKey as DealMilestone,
      autoGenerated: true,
    };
  });
}
