// Shared AI Action Approval Engine — Phase 3D
// Handles approve/dismiss for all AI-suggested actions across chat, voice, search.
// Pattern: AI suggests → user approves via this engine → app writes → audit logged.

import type { Deal } from '../types';
import type { DealChatAction } from './types';
import { logAIAudit, type AISource } from './aiAuditLogger';

export interface ApprovalResult {
  success: boolean;
  message: string;
  updatedDeal?: Deal;
}

export async function approveAction(
  action: DealChatAction,
  deal: Deal,
  source: AISource,
  extra?: Record<string, unknown>,
): Promise<ApprovalResult> {
  const p = action.payload as Record<string, unknown>;

  switch (action.type) {
    case 'create_task': {
      const newTask = {
        id: `task-${Date.now()}`,
        title: String(p.title || ''),
        dueDate: String(p.dueDate || new Date().toISOString().split('T')[0]),
        priority: (['high', 'medium', 'low'].includes(String(p.priority)) ? String(p.priority) : 'medium') as 'high' | 'medium' | 'low',
        category: String(p.targetRole || 'General'),
        milestone: deal.milestone,
        autoGenerated: false,
        notes: String(p.description || ''),
        completedAt: undefined,
        completedBy: undefined,
      };
      const updatedDeal = { ...deal, tasks: [...(deal.tasks || []), newTask] };
      await logAIAudit({
        action: 'ai_task_created',
        entityType: 'task',
        entityId: newTask.id,
        entityName: newTask.title,
        source,
        aiAction: action,
        approved: true,
        extra,
      });
      return { success: true, message: `Task created: ${newTask.title}`, updatedDeal };
    }

    case 'add_note': {
      const noteEntry = {
        id: `act-${Date.now()}`,
        timestamp: new Date().toISOString(),
        action: String(p.title || 'AI Note'),
        detail: String(p.description || ''),
        user: source === 'voice_update' ? 'AI Voice' : 'AI Assistant',
        type: 'note' as const,
      };
      const updatedDeal = { ...deal, activityLog: [noteEntry, ...(deal.activityLog || [])] };
      await logAIAudit({
        action: 'ai_note_added',
        entityType: 'note',
        entityId: noteEntry.id,
        entityName: noteEntry.action,
        source,
        aiAction: action,
        approved: true,
        extra,
      });
      return { success: true, message: `Note added: ${noteEntry.action}`, updatedDeal };
    }

    case 'flag_compliance_issue': {
      await logAIAudit({
        action: 'ai_compliance_flagged',
        entityType: 'compliance',
        entityId: deal.id,
        entityName: String(p.title || ''),
        source,
        aiAction: action,
        approved: true,
        extra,
      });
      return { success: true, message: `Compliance issue flagged: ${String(p.title || '')}` };
    }

    case 'draft_email': {
      await logAIAudit({
        action: 'ai_email_drafted',
        entityType: 'email',
        entityId: deal.id,
        entityName: String(p.title || ''),
        source,
        aiAction: action,
        approved: true,
        extra,
      });
      return {
        success: true,
        message: `Email draft ready — Subject: ${String(p.title || '')}\n\n${String(p.description || '')}\n\nCopy to Email tab to send.`,
      };
    }

    case 'suggest_stage_update': {
      await logAIAudit({
        action: 'ai_stage_suggestion',
        entityType: 'deal',
        entityId: deal.id,
        entityName: `${deal.milestone} → ${String(p.title || '')}`,
        source,
        aiAction: action,
        approved: true,
        extra,
      });
      return {
        success: true,
        message: `Stage update noted: consider moving to ${String(p.title || '')}. Update manually in Edit Deal for safety.`,
      };
    }

    default:
      return { success: false, message: `Unknown action type: ${action.type}` };
  }
}

export async function dismissAction(
  action: DealChatAction,
  dealId: string,
  source: AISource,
  extra?: Record<string, unknown>,
): Promise<void> {
  await logAIAudit({
    action: 'ai_action_dismissed',
    entityType: 'deal',
    entityId: dealId,
    entityName: action.type,
    source,
    aiAction: action,
    approved: false,
    extra,
  });
}
