import React, { useState } from 'react';
import { Sparkles, CheckCircle2, AlertCircle, Plus, ChevronDown, ChevronUp } from 'lucide-react';
import { Deal, ChecklistItem } from '../types';
import { generateId } from '../utils/helpers';
import { StatusBadge } from './ui/StatusBadge';

interface Props {
  deal: Deal;
  onUpdate: (d: Deal) => void;
}

interface DDSuggestion {
  title: string;
  reason: string;
  priority: 'high' | 'medium' | 'low';
}

interface CompSuggestion {
  title: string;
  reason: string;
  required: boolean;
}

interface SuggestResult {
  dueDiligenceItems: DDSuggestion[];
  complianceItems: CompSuggestion[];
  explanation: string;
}


export const SmartChecklistSuggestions: React.FC<Props> = ({ deal, onUpdate }) => {
  const [result, setResult] = useState<SuggestResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [selectedDD, setSelectedDD] = useState<Set<number>>(new Set());
  const [selectedComp, setSelectedComp] = useState<Set<number>>(new Set());
  const [expanded, setExpanded] = useState(true);
  const [added, setAdded] = useState(false);

  const handleSuggest = async () => {
    setLoading(true);
    setError('');
    setResult(null);
    setSelectedDD(new Set());
    setSelectedComp(new Set());
    setAdded(false);
    try {
      const existingDD = deal.dueDiligenceChecklist.map(i => i.title);
      const existingComp = deal.complianceChecklist.map(i => i.title);
      const res = await fetch('/api/ai?action=suggest-checklist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          deal: {
            propertyAddress: deal.propertyAddress,
            city: deal.city,
            state: deal.state,
            propertyType: deal.propertyType,
            transactionType: deal.transactionType,
            contractPrice: deal.contractPrice,
            listPrice: deal.listPrice,
            closingDate: deal.closingDate,
            contractDate: deal.contractDate,
            milestone: deal.milestone,
            status: deal.status,
          },
          existingDDTitles: existingDD,
          existingCompTitles: existingComp,
        }),
      });
      if (!res.ok) throw new Error('AI suggestion request failed');
      const data: SuggestResult = await res.json();
      setResult(data);
      // Auto-select all
      setSelectedDD(new Set(data.dueDiligenceItems.map((_, i) => i)));
      setSelectedComp(new Set(data.complianceItems.map((_, i) => i)));
    } catch (err: any) {
      setError(err.message || 'Failed to get suggestions');
    } finally {
      setLoading(false);
    }
  };

  const toggleDD = (idx: number) => {
    setSelectedDD(prev => {
      const n = new Set(prev);
      n.has(idx) ? n.delete(idx) : n.add(idx);
      return n;
    });
  };

  const toggleComp = (idx: number) => {
    setSelectedComp(prev => {
      const n = new Set(prev);
      n.has(idx) ? n.delete(idx) : n.add(idx);
      return n;
    });
  };

  const handleAddSelected = () => {
    if (!result) return;
    const newDD: ChecklistItem[] = [];
    const newComp: ChecklistItem[] = [];

    selectedDD.forEach(idx => {
      const item = result.dueDiligenceItems[idx];
      if (item) {
        newDD.push({
          id: generateId(),
          title: item.title,
          completed: false,
          autoGenerated: true,
          source: 'ai-suggestion',
        });
      }
    });

    selectedComp.forEach(idx => {
      const item = result.complianceItems[idx];
      if (item) {
        newComp.push({
          id: generateId(),
          title: item.title,
          completed: false,
          required: item.required,
          autoGenerated: true,
          source: 'ai-suggestion',
        });
      }
    });

    if (newDD.length === 0 && newComp.length === 0) return;

    onUpdate({
      ...deal,
      dueDiligenceChecklist: [...deal.dueDiligenceChecklist, ...newDD],
      complianceChecklist: [...deal.complianceChecklist, ...newComp],
      activityLog: [
        ...deal.activityLog,
        {
          id: generateId(),
          timestamp: new Date().toISOString(),
          action: 'AI checklist items added',
          detail: `Added ${newDD.length} DD and ${newComp.length} compliance items from AI suggestions`,
          user: 'AI Assistant',
          type: 'checklist' as const,
        },
      ],
      updatedAt: new Date().toISOString(),
    });
    setAdded(true);
  };

  const totalSelected = selectedDD.size + selectedComp.size;
  const hasResults = result && (result.dueDiligenceItems.length > 0 || result.complianceItems.length > 0);

  return (
    <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-xl mb-4">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-2.5">
        <div className="flex items-center gap-2">
          <Sparkles size={15} className="text-purple-500" />
          <span className="text-sm font-semibold text-purple-700">Smart Checklist Suggestions</span>
        </div>
        <div className="flex items-center gap-2">
          {!result && !loading && (
            <button
              onClick={handleSuggest}
              className="btn btn-xs bg-purple-500 hover:bg-purple-600 text-white border-0 gap-1"
            >
              <Sparkles size={11} /> AI Suggest Items
            </button>
          )}
          {result && (
            <button onClick={() => setExpanded(!expanded)} className="btn btn-ghost btn-xs">
              {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </button>
          )}
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <LoadingSpinner />
      )}

      {/* Error */}
      {error && (
        <div className="px-4 pb-3">
          <div className="alert alert-error text-xs py-2">
            {error}
            <button className="btn btn-ghost btn-xs" onClick={handleSuggest}>Retry</button>
          </div>
        </div>
      )}

      {/* Results */}
      {result && expanded && (
        <div className="px-4 pb-4 space-y-3">
          {/* Explanation */}
          <p className="text-xs text-purple-600/80">{result.explanation}</p>

          {/* Added confirmation */}
          {added && (
            <div className="flex items-center gap-2 p-2 bg-green-50 border border-green-200 rounded-lg">
              <CheckCircle2 size={14} className="text-green-500" />
              <span className="text-xs text-green-700 font-medium">Items added to checklists!</span>
              <button onClick={handleSuggest} className="btn btn-ghost btn-xs ml-auto text-purple-500">Get More</button>
            </div>
          )}

          {!added && hasResults && (
            <>
              {/* DD Suggestions */}
              {result.dueDiligenceItems.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-base-content/60 uppercase mb-1.5">Due Diligence</p>
                  <div className="space-y-1">
                    {result.dueDiligenceItems.map((item, i) => (
                      <label key={i} className="flex items-start gap-2 p-2 bg-white/80 rounded-lg border border-base-200 cursor-pointer hover:bg-white transition-colors">
                        <input
                          type="checkbox"
                          checked={selectedDD.has(i)}
                          onChange={() => toggleDD(i)}
                          className="checkbox checkbox-xs checkbox-primary mt-0.5"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-1.5">
                            <span className="text-sm font-medium text-base-content">{item.title}</span>
                            <StatusBadge status={item.priority} />
                          </div>
                          <p className="text-xs text-base-content/50">{item.reason}</p>
                        </div>
                      </label>
                    ))}
                  </div>
                </div>
              )}

              {/* Compliance Suggestions */}
              {result.complianceItems.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-base-content/60 uppercase mb-1.5">Compliance</p>
                  <div className="space-y-1">
                    {result.complianceItems.map((item, i) => (
                      <label key={i} className="flex items-start gap-2 p-2 bg-white/80 rounded-lg border border-base-200 cursor-pointer hover:bg-white transition-colors">
                        <input
                          type="checkbox"
                          checked={selectedComp.has(i)}
                          onChange={() => toggleComp(i)}
                          className="checkbox checkbox-xs checkbox-secondary mt-0.5"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-1.5">
                            <span className="text-sm font-medium text-base-content">{item.title}</span>
                            {item.required && <span className="badge badge-xs badge-error">Required</span>}
                          </div>
                          <p className="text-xs text-base-content/50">{item.reason}</p>
                        </div>
                      </label>
                    ))}
                  </div>
                </div>
              )}

              {/* Add button */}
              <div className="flex items-center justify-between pt-1">
                <span className="text-xs text-base-content/50">{totalSelected} item{totalSelected !== 1 ? 's' : ''} selected</span>
                <button
                  onClick={handleAddSelected}
                  disabled={totalSelected === 0}
                  className="btn btn-sm bg-purple-500 hover:bg-purple-600 text-white border-0 gap-1"
                >
                  <Plus size={13} /> Add Selected
                </button>
              </div>
            </>
          )}

          {!added && !hasResults && (
            <div className="flex items-center gap-2 p-2 bg-green-50 border border-green-200 rounded-lg">
              <CheckCircle2 size={14} className="text-green-500" />
              <span className="text-xs text-green-700 font-medium">Your checklists look comprehensive! No additional items suggested.</span>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
