export interface ConfirmationButton {
  id: string;
  label: string;       // e.g. "Confirm Receipt"
  replyText: string;   // pre-filled reply body e.g. "I confirm receipt of documents for {{address}}"
}

export interface EmailTemplate {
  id: string;
  name: string;           // display name e.g. "Introduction Email"
  subject: string;        // supports {{merge}} tags
  body: string;           // supports {{merge}} tags
  buttons: ConfirmationButton[];
  isDefault?: boolean;
  createdAt: string;
  updatedAt: string;
}

export type DealMilestone =
  | 'contract-received'
  | 'emd-due'
  | 'inspections-due'
  | 'appraisal-ordered'
  | 'appraisal-received'
  | 'title-opened'
  | 'loan-commitment'
  | 'closing-scheduled'
  | 'clear-to-close'
  | 'closed'
  | 'archived';

export type TaskPriority = 'high' | 'medium' | 'low';

export interface DealTask {
  id: string;
  title: string;
  dueDate: string;          // YYYY-MM-DD
  completedAt?: string;
  completedBy?: string;
  priority: TaskPriority;
  category: string;         // e.g. 'Financial', 'Legal', 'Compliance'
  milestone: DealMilestone; // which milestone generated/created this task
  autoGenerated: boolean;
  notes?: string;
}

export type UserRole = 'admin' | 'tc' | 'staff';
export interface DDMasterItem {
  id: string;
  title: string;
  required: boolean;
  order: number;
}

export interface AppUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  active: boolean;
  createdAt: string;
}
export type DealStatus = 'contract' | 'due-diligence' | 'clear-to-close' | 'closed' | 'terminated';
export type TransactionSide = 'buyer' | 'seller';
export type PropertyType = 'single-family' | 'multi-family' | 'condo' | 'townhouse' | 'land' | 'commercial';
export type ContactRole = 'agent' | 'agent-client' | 'buyer' | 'seller' | 'lender' | 'title' | 'attorney' | 'inspector' | 'tc' | 'other';

export interface ComplianceMasterItem {
  id: string;
  title: string;
  order: number;
}

export interface ComplianceTemplateItem {
  id: string;
  title: string;
  required: boolean;
  order: number;
  masterId?: string;   // set if this item came from the master list
  isCustom?: boolean;  // set if manually added to this template only
}

export interface ComplianceTemplate {
  id: string;
  name: string;                    // e.g. "Illinois Standard", "Kansas City Template"
  description?: string;
  state?: string;                  // US state this template applies to (e.g. "Illinois")
  agentClientIds: string[];        // Agent Clients assigned to this template
  inspectionPeriodDays?: number;   // Used in email merge tag {{inspectionDeadline}}
  items: ComplianceTemplateItem[];
  createdAt: string;
  updatedAt: string;
  // legacy fields kept for migration compatibility
  agentClientId?: string;
  agentClientName?: string;
}

export interface MlsDocument {
  id: string;
  name: string;
  category: 'listing' | 'disclosure' | 'addendum' | 'contract' | 'compliance' | 'other';
  required: boolean;
  notes?: string;
}

export interface MlsEntry {
  id: string;
  name: string;
  url: string;
  state: string;
  notes?: string;
  createdAt: string;
  documents: MlsDocument[];
}
export type DocRequestType =
  | 'price_amendment'
  | 'mf_addendum'
  | 'closing_date_extension'
  | 'inspection_addendum'
  | 'repair_addendum'
  | 'hoa_addendum'
  | 'lead_paint_addendum'
  | 'custom';
export type DocRequestStatus = 'pending' | 'in_progress' | 'confirmed';
export type ActivityType =
  | 'deal_created' | 'status_change' | 'checklist' | 'contact_added'
  | 'document_requested' | 'document_confirmed' | 'reminder_set' | 'note' | 'price_change';

/** Per-state profile info for an Agent Client */
export interface AgentClientStateInfo {
  state: string;               // e.g. "FL"
  closingType: 'escrow' | 'attorney' | '';   // how closings work in this state
  commissionType: 'commission-letter' | 'cda' | '';  // how commission is requested
  brokerEmail: string;
  brokerPhone: string;
  complianceEmail: string;
  compliancePhone: string;
  eSignatureApp: string;
  links: string[];             // zero or more resource URLs
}

/** Master directory contact — lives in the global contact book */
export interface DirectoryContact {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: ContactRole;
  company?: string;
  states?: string[];   // states they operate in (optional filter)
  mlsIds?: string[];   // MLS entries they are associated with
  stateInfo?: AgentClientStateInfo[];  // per-state details (agent-client only)
  clientId?: string;   // unique ID: AC-<last4 of phone> (agent-client only)
  isTeam?: boolean;    // does this agent client have a team?
  teamRoles?: string[]; // roles present on the team (e.g. 'tc', 'showing_agent', etc.)
  notes?: string;
  createdAt: string;
}

/** Deal-level contact — linked from directory, has deal-specific fields */
export interface AdditionalPerson {
  id: string;
  name: string;
  relationship: string;
  maritalStatus: string;
  phone: string;
  email: string;
}

export interface Contact {
  id: string;
  directoryId?: string;  // reference back to DirectoryContact.id
  name: string;
  email: string;
  phone: string;
  role: ContactRole;
  company?: string;
  inNotificationList: boolean;
  side?: 'buy' | 'sell' | 'both';  // which side of the transaction
  additionalPeople?: AdditionalPerson[];
}

export interface ChecklistItem {
  autoGenerated?: boolean;   // true = injected by property-type rule
  source?: string;           // e.g. 'auto-condo' | 'auto-multifamily'
  id: string;
  title: string;
  completed: boolean;
  dueDate?: string;
  notes?: string;
  completedAt?: string;
  completedBy?: string;
  category?: string;   // DD checklist section grouping
  required?: boolean;  // flags item as mandatory
}

export interface DocumentRequest {
  id: string;
  type: DocRequestType;
  label: string;
  description: string;
  requestedAt: string;
  requestedBy: string;
  status: DocRequestStatus;
  confirmedBy?: string;
  confirmedAt?: string;
  notes?: string;
  urgency: 'high' | 'medium' | 'low';
}

export interface Reminder {
  id: string;
  title: string;
  dueDate: string;
  notes?: string;
  completed: boolean;
}

export interface ActivityEntry {
  id: string;
  timestamp: string;
  action: string;
  detail?: string;
  user: string;
  type: ActivityType;
}

export interface AgentContact {
  name: string;
  phone: string;
  email: string;
  isOurClient: boolean;
}

export interface Deal {
  id: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  mlsNumber: string;
  listPrice: number;
  contractPrice: number;
  propertyType: PropertyType;
  status: DealStatus;
  transactionSide: TransactionSide;
  contractDate: string;
  closingDate: string;
  agentId: string;
  agentName: string;
  agentClientId?: string;
  complianceTemplateId?: string;
  buyerAgent?: AgentContact;
  sellerAgent?: AgentContact;
  contacts: Contact[];
  dueDiligenceChecklist: ChecklistItem[];
  complianceChecklist: ChecklistItem[];
  documentRequests: DocumentRequest[];
  reminders: Reminder[];
  activityLog: ActivityEntry[];
  notes: string;
  archiveReason?: string;
  milestone: DealMilestone;
  tasks: DealTask[];
  createdAt: string;
  updatedAt: string;
}

// ── Inbox / Messaging ────────────────────────────────────────────────────────

export interface ConversationParticipant {
  contact_id: string | null;
  name: string;
  phone: string;
}

export interface Conversation {
  id: string;
  name: string;
  deal_id: string | null;
  type: 'direct' | 'broadcast' | 'group';
  channel: 'sms' | 'email';
  participants: ConversationParticipant[];
  last_message_at: string | null;
  last_message_preview: string | null;
  unread_count: number;
  created_at: string;
  updated_at: string;
}

export interface SmsMessage {
  id: string;
  conversation_id: string | null;
  deal_id: string | null;
  contact_id: string | null;
  direction: 'inbound' | 'outbound';
  channel: 'sms' | 'email';
  body: string;
  status: 'sent' | 'delivered' | 'received' | 'failed';
  from_number: string | null;
  to_number: string | null;
  external_message_id: string | null;
  auto_created_task_id: string | null;
  sent_at: string;
  created_at: string;
}
