export interface ConfirmationButton {
  id: string;
  label: string;       // e.g. "Confirm Receipt"
  replyText: string;   // pre-filled reply body e.g. "I confirm receipt of documents for {{address}}"
}

export interface EmailTemplate {
  id: string;
  name: string;           // display name e.g. "Introduction Email"
  subject: string;        // supports {{merge}} tags
  body: string;           // supports {{merge}} tags
  buttons: ConfirmationButton[];
  isDefault?: boolean;
  createdAt: string;
  updatedAt: string;
}

export type DealMilestone =
  | 'contract-received'
  | 'emd-due'
  | 'inspections-due'
  | 'appraisal-ordered'
  | 'appraisal-received'
  | 'title-opened'
  | 'loan-commitment'
  | 'closing-scheduled'
  | 'clear-to-close'
  | 'closed'
  | 'archived';

export type TaskPriority = 'high' | 'medium' | 'low';

export interface DealTask {
  id: string;
  title: string;
  dueDate: string;          // YYYY-MM-DD
  completedAt?: string;
  completedBy?: string;
  priority: TaskPriority;
  category: string;         // e.g. 'Financial', 'Legal', 'Compliance'
  milestone: DealMilestone; // which milestone generated/created this task
  autoGenerated: boolean;
  notes?: string;
}

export type UserRole = 'admin' | 'tc' | 'staff';
export interface DDMasterItem {
  id: string;
  title: string;
  required: boolean;
  order: number;
}

export interface AppUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  active: boolean;
  createdAt: string;
}
export type DealStatus = 'contract' | 'due-diligence' | 'clear-to-close' | 'closed' | 'terminated';
export type TransactionSide = 'buyer' | 'seller';
export type TransactionType = 'buyer' | 'seller' | 'dual' | 'listing';
export type PropertyType = 'single-family' | 'multi-family' | 'condo' | 'townhouse' | 'land' | 'commercial';
export type ContactRole = 'agent' | 'buyer' | 'seller' | 'lender' | 'title' | 'attorney' | 'inspector' | 'appraiser' | 'tc' | 'other';

// ── New relational type aliases ──────────────────────────────────────────────
export type ContactType = ContactRole; // alias for clarity during migration
export type OrganizationType = 'team' | 'brokerage' | 'title_company' | 'lender_company' | 'builder' | 'vendor';
export type DealSide = 'listing' | 'buyer' | 'seller' | 'vendor' | 'internal';
export type DealParticipantRole = 'lead_agent' | 'co_agent' | 'admin' | 'tc' | 'lender' | 'title_officer' | 'buyer' | 'seller' | 'inspector' | 'appraiser' | 'other';
export type LicenseType = 'salesperson' | 'broker' | 'associate_broker';
export type LicenseStatus = 'active' | 'inactive' | 'expired' | 'pending';
export type MlsMembershipStatus = 'active' | 'inactive' | 'suspended';
export type ClientAccountType = 'individual_agent' | 'team';
export type ClientAccountStatus = 'active' | 'inactive' | 'former' | 'prospect';
export type OrgMemberRole = 'lead_agent' | 'agent' | 'admin' | 'tc' | 'broker' | 'loan_officer' | 'title_officer' | 'staff';

// ── Organizations ────────────────────────────────────────────────────────────

export interface Organization {
  id: string;
  name: string;
  organizationType: OrganizationType;
  email?: string;
  phone?: string;
  address?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface OrganizationMember {
  id: string;
  organizationId: string;
  contactId: string;
  roleInOrganization: OrgMemberRole;
  isPrimary: boolean;
  isActive: boolean;
  startDate?: string;
  endDate?: string;
  createdAt: string;
  updatedAt: string;
  // Joined fields (populated by data layer)
  organizationName?: string;
  contactName?: string;
}

// ── Client Accounts ──────────────────────────────────────────────────────────

export interface ClientAccount {
  id: string;
  accountName: string;
  accountType: ClientAccountType;
  primaryContactId?: string;
  primaryOrganizationId?: string;
  status: ClientAccountStatus;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  // Joined fields
  primaryContactName?: string;
  primaryOrganizationName?: string;
}

export interface ClientAccountMember {
  id: string;
  clientAccountId: string;
  contactId?: string;
  organizationId?: string;
  relationshipRole: 'primary_client' | 'admin' | 'tc' | 'support_agent' | 'team_member';
  isPrimary: boolean;
  isActive: boolean;
  startDate?: string;
  endDate?: string;
  createdAt: string;
  updatedAt: string;
}

// ── Contact Licenses & MLS ───────────────────────────────────────────────────

export interface ContactLicense {
  id: string;
  contactId: string;
  stateCode: string;
  licenseType: LicenseType;
  licenseNumber: string;
  status: LicenseStatus;
  brokerOrganizationId?: string;
  issueDate?: string;
  expirationDate?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  // Joined fields
  brokerOrganizationName?: string;
}

export interface ContactMlsMembership {
  id: string;
  contactId: string;
  mlsName: string;
  mlsCode?: string;
  mlsMemberNumber: string;
  officeMlsNumber?: string;
  stateCode?: string;
  brokerOrganizationId?: string;
  boardName?: string;
  status: MlsMembershipStatus;
  startDate?: string;
  endDate?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// ── Deal Participants ────────────────────────────────────────────────────────

export interface DealParticipant {
  id: string;
  dealId: string;
  contactId?: string;
  organizationId?: string;
  clientAccountId?: string;
  side: DealSide;
  dealRole: DealParticipantRole;
  isPrimary: boolean;
  isClientSide: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  // Joined fields (populated by data layer)
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  organizationName?: string;
}

// ── Compliance ───────────────────────────────────────────────────────────────

export interface ComplianceMasterItem {
  id: string;
  title: string;
  order: number;
}

export interface ComplianceTemplateItem {
  id: string;
  title: string;
  required: boolean;
  order: number;
  masterId?: string;
  isCustom?: boolean;
}

export interface ComplianceTemplate {
  id: string;
  name: string;
  description?: string;
  state?: string;
  agentClientIds: string[];
  inspectionPeriodDays?: number;
  items: ComplianceTemplateItem[];
  createdAt: string;
  updatedAt: string;
  agentClientId?: string;
  agentClientName?: string;
}

// ── MLS ──────────────────────────────────────────────────────────────────────

export interface MlsDocument {
  id: string;
  name: string;
  category: 'listing' | 'disclosure' | 'addendum' | 'contract' | 'compliance' | 'other';
  required: boolean;
  notes?: string;
}

export interface MlsEntry {
  id: string;
  name: string;
  url: string;
  state: string;
  notes?: string;
  createdAt: string;
  documents: MlsDocument[];
}
export type DocRequestType =
  | 'price_amendment'
  | 'mf_addendum'
  | 'closing_date_extension'
  | 'inspection_addendum'
  | 'repair_addendum'
  | 'hoa_addendum'
  | 'lead_paint_addendum'
  | 'custom';
export type DocRequestStatus = 'pending' | 'in_progress' | 'confirmed';
export type ActivityType =
  | 'deal_created' | 'status_change' | 'checklist' | 'contact_added'
  | 'document_requested' | 'document_confirmed' | 'reminder_set' | 'note' | 'price_change';

export interface AdditionalPerson {
  id: string;
  name: string;
  relationship: string;
  maritalStatus: string;
  phone: string;
  email: string;
}

export interface Contact {
  id: string;
  directoryId?: string;
  name: string;
  fullName?: string;       // Phase 4: computed from first_name + last_name
  firstName?: string;      // Phase 4: from contacts table
  lastName?: string;       // Phase 4: from contacts table
  email: string;
  phone: string;
  role: ContactRole;
  contactType?: ContactType;  // Phase 4: same as role, clearer name
  company?: string;
  timezone?: string;       // Phase 4: IANA timezone
  inNotificationList: boolean;
  side?: 'buy' | 'sell' | 'both';
  additionalPeople?: AdditionalPerson[];
  // Phase 4: relational joins (populated by data layer)
  organizations?: OrganizationMember[];
  licenses?: ContactLicense[];
  mlsMemberships?: ContactMlsMembership[];
  clientAccountId?: string;
}

// ── Contact Record (enriched from relational tables) ────────────────────────
export interface ContactRecord {
  id: string;
  firstName: string;
  lastName: string;
  fullName: string;
  email: string;
  phone: string;
  contactType: ContactRole;
  company: string;
  timezone: string;
  notes: string;
  isActive: boolean;
  createdAt: string;
  licenses: ContactLicense[];
  mlsMemberships: ContactMlsMembership[];
  organizations: OrgMemberInfo[];
  isClient: boolean;
  clientAccountId?: string;
}

export interface OrgMemberInfo {
  membershipId: string;
  organizationId: string;
  organizationName: string;
  organizationType: string;
  roleInOrganization: string;
}

export interface ChecklistItem {
  autoGenerated?: boolean;
  source?: string;
  id: string;
  title: string;
  completed: boolean;
  dueDate?: string;
  notes?: string;
  completedAt?: string;
  completedBy?: string;
  category?: string;
  required?: boolean;
}

export interface DocumentRequest {
  id: string;
  type: DocRequestType;
  label: string;
  description: string;
  requestedAt: string;
  requestedBy: string;
  status: DocRequestStatus;
  confirmedBy?: string;
  confirmedAt?: string;
  notes?: string;
  urgency: 'high' | 'medium' | 'low';
}

export interface Reminder {
  id: string;
  title: string;
  dueDate: string;
  notes?: string;
  completed: boolean;
}

export interface ActivityEntry {
  id: string;
  timestamp: string;
  action: string;
  detail?: string;
  user: string;
  type: ActivityType;
}

/**
 * @deprecated Use DealParticipant instead. Will be removed in Phase 4D.
 */
export interface AgentContact {
  name: string;
  phone: string;
  email: string;
  isOurClient: boolean;
}

export interface Deal {
  id: string;

  // ── Property info ──────────────────────────────────────────────────────────
  propertyAddress: string;       // Phase 4: canonical name (was `address`)
city: string;
  state: string;
  zipCode: string;
  legalDescription?: string;
  mlsNumber: string;
  listPrice: number;
  contractPrice: number;
  propertyType: PropertyType;

  // ── Deal status ────────────────────────────────────────────────────────────
  status: DealStatus;
  milestone: DealMilestone;
  transactionType: TransactionType;    // Phase 4: canonical (was transactionSide)
riskLevel?: string;                  // Phase 4: 'normal' | 'elevated' | 'high'

  // ── Dates ──────────────────────────────────────────────────────────────────
  contractDate: string;
  closingDate: string;

  // ── Relationships (Phase 4 relational) ─────────────────────────────────────
  primaryClientAccountId?: string;     // FK to client_accounts
  assignedTcUserId?: string;           // FK to profiles
  assignedComplianceUserId?: string;   // FK to profiles
  participants?: DealParticipant[];    // Loaded from deal_participants table

  // ── Legacy agent fields (populated from participants for backward compat) ──
  /** @deprecated Use participants with is_client_side=true instead */
  agentId: string;
  /** @deprecated Use participants with is_client_side=true instead */
  agentName: string;
  /** @deprecated Use clientAccount lookup instead */
  agentClientId?: string;
  complianceTemplateId?: string;
  /** @deprecated Use participants with side='buyer' and deal_role='lead_agent' */
  buyerAgent?: AgentContact;
  /** @deprecated Use participants with side='listing' and deal_role='lead_agent' */
  sellerAgent?: AgentContact;

  // ── Embedded arrays (kept during transition, tasks/checklists still in JSONB) ─
  /** @deprecated Will be replaced by deal_participants in 4D */
  contacts: Contact[];
  dueDiligenceChecklist: ChecklistItem[];
  complianceChecklist: ChecklistItem[];
  documentRequests: DocumentRequest[];
  reminders: Reminder[];
  activityLog: ActivityEntry[];
  tasks: DealTask[];

  notes: string;
  archiveReason?: string;
  createdAt: string;
  updatedAt: string;
}

// ── Inbox / Messaging ────────────────────────────────────────────────────────

export interface ConversationParticipant {
  contact_id: string | null;
  name: string;
  phone: string;
}

export interface Conversation {
  id: string;
  name: string;
  deal_id: string | null;
  type: 'direct' | 'broadcast' | 'group';
  channel: 'sms' | 'email' | 'whatsapp';
  participants: ConversationParticipant[];
  last_message_at: string | null;
  last_message_preview: string | null;
  unread_count: number;
  created_at: string;
  updated_at: string;
}

export interface SmsMessage {
  id: string;
  conversation_id: string | null;
  deal_id: string | null;
  contact_id: string | null;
  direction: 'inbound' | 'outbound';
  channel: 'sms' | 'email' | 'whatsapp';
  body: string;
  status: 'sent' | 'delivered' | 'received' | 'failed';
  from_number: string | null;
  to_number: string | null;
  external_message_id: string | null;
  auto_created_task_id: string | null;
  sent_at: string;
  created_at: string;
}

// ── Voice + AI (Phase 5) ─────────────────────────────────────────────────────

export interface ContactPhoneChannel {
  id: string;
  contactId: string;
  clientAccountId?: string;
  phoneE164: string;
  label?: string;
  isVerified: boolean;
  canCallIn: boolean;
  canReceiveTexts: boolean;
  canRequestUpdates: boolean;
  canSubmitVoiceUpdates: boolean;
  canRequestCallback: boolean;
  isPrimary: boolean;
  status: 'active' | 'inactive' | 'blocked';
  createdAt: string;
  updatedAt: string;
  // Joined display fields
  contactName?: string;
  contactType?: string;
}

export interface VoiceAnalysis {
  containsChangeRequest: boolean;
  changeType?: string;
  impactLevel?: string;
  suggestedActions?: string[];
  sentiment?: string;
  keyEntities?: string[];
}

export interface VoiceSuggestedAction {
  type: string;
  description: string;
}

export interface VoiceDealUpdate {
  id: string;
  dealId?: string;
  callerContactId?: string;
  callerClientAccountId?: string;
  phoneE164: string;
  callSid?: string;
  recordingSid?: string;
  recordingUrl?: string;
  recordingDuration?: number;
  transcript?: string;
  aiSummary?: string;
  aiAnalysis?: VoiceAnalysis;
  suggestedActions?: VoiceSuggestedAction[];
  confidenceLevel: 'high' | 'medium' | 'low';
  reviewStatus: 'pending' | 'reviewed' | 'applied' | 'dismissed';
  reviewedBy?: string;
  reviewedAt?: string;
  createdAt: string;
  updatedAt: string;
  contactName?: string;
  dealAddress?: string;
}

export interface CallbackRequest {
  id: string;
  dealId?: string;
  callerContactId?: string;
  callerClientAccountId?: string;
  phoneE164: string;
  requestedByChannel: 'voice' | 'sms';
  reason?: string;
  priority: 'low' | 'normal' | 'high' | 'urgent';
  status: 'open' | 'acknowledged' | 'completed' | 'dismissed';
  assignedUserId?: string;
  requestedAt: string;
  acknowledgedAt?: string;
  completedAt?: string;
  notes?: string;
  contactName?: string;
  dealAddress?: string;
}

export interface CommunicationEvent {
  id: string;
  dealId?: string;
  contactId?: string;
  clientAccountId?: string;
  channel: 'voice' | 'sms' | 'email' | 'whatsapp';
  direction: 'inbound' | 'outbound';
  eventType: 'status_request' | 'voice_update' | 'callback_request' | 'sms_command' | 'general';
  summary?: string;
  transcript?: string;
  recordingUrl?: string;
  sourceRef?: string;
  metadata?: Record<string, unknown>;
  createdAt: string;
  contactName?: string;
  dealAddress?: string;
}

export type ChangeType = 'closing_date' | 'price_change' | 'inspection' | 'repair_request' |
  'cancellation' | 'contract_term' | 'possession' | 'document_update' | 'other';

export type ChangeImpact = 'low' | 'medium' | 'high' | 'critical';

export type ChangeStatus = 'pending_review' | 'needs_clarification' | 'approved' | 'rejected' | 'applied';

export interface ChangeRequest {
  id: string;
  dealId: string;
  requestedByContactId?: string;
  requestedByClientAccountId?: string;
  sourceEventId?: string;
  sourceChannel: 'voice' | 'sms' | 'email';
  changeType: ChangeType;
  requestedChangeText: string;
  aiStructuredPayload?: Record<string, unknown>;
  impactLevel: ChangeImpact;
  status: ChangeStatus;
  assignedReviewerUserId?: string;
  reviewedByUserId?: string;
  reviewedAt?: string;
  appliedAt?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  contactName?: string;
  dealAddress?: string;
}

export interface AmbiguityQueueItem {
  id: string;
  channel: 'voice' | 'sms';
  phoneE164: string;
  body?: string;
  callSid?: string;
  likelyContactIds?: string[];
  likelyDealIds?: string[];
  confidenceLevel: 'low' | 'medium';
  status: 'open' | 'resolved' | 'dismissed';
  resolvedBy?: string;
  resolutionNotes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CallerContext {
  phoneChannel: ContactPhoneChannel;
  contact: {
    id: string;
    firstName: string;
    lastName: string;
    fullName: string;
    email: string;
    phone: string;
    contactType: string;
  };
  clientAccount?: {
    id: string;
    accountName: string;
    status: string;
  };
  activeDeals: Array<{
    id: string;
    propertyAddress: string;
    milestone: string;
    closingDate?: string;
    city?: string;
    state?: string;
  }>;
}
